Startseite
denis-kasak/uni-webdev pull request #6
Opened 2023-01-28 21:36 UTC by instantcreator

Ich habe eine farblich bunte und sonst recht generische Startseite erschaffen, welche durch ihre Farbgebung prinzipien des grids und des Webaufbaus verdeutlicht.

2023-01-28 21:44 UTC, denis-kasak requested changes
Bitte noch mindestens zwei Bilder einfügen ;)

2023-01-28 23:43 UTC, denis-kasak requested changes
Bilder werden nicht geladen (paths von <link sind falsch). Schrift ist weiß auf weißem Hintergrund

![image](https://user-images.githubusercontent.com/91327614/215296153-7ee5d168-08a3-400e-877b-89691ebe90b2.png)

2023-01-29 18:11 UTC, instantcreator commented
Hintergrundbild nachgeladen und Tabicon hinzuigefügt. Müsste jetzt alle Kriterien erfüllen.

2023-01-30 13:27 UTC, denis-kasak approved these changes

2023-01-30 13:27 UTC, merged